# Generated by Django 6.1.1 on 2026-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='max_messenger',
            field=models.URLField(blank=True, null=True, verbose_name='MAX'),
        ),
    ]
