# Generated by Django 6.1.1 on 2026-09-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Согласие с офертой'),
        ),
    ]
