# Generated by Django 6.1.1 on 2026-09-14 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_video_alter_course_video_url'),
        ('portfolio', '0001_initial'),
        ('users', '0002_customuser_agreed_at_customuser_agreed_to_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='portfolio.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('work__isnull', False)), fields=('user', 'work'), name='unique_user_work_favorite'), models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('user', 'course'), name='unique_user_course_favorite')],
            },
        ),
    ]
