# Generated by Django 6.1.1 on 2026-09-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='consent_mailing',
            field=models.BooleanField(default=False, verbose_name='Согласие на рассылку'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_pd',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
    ]
