# Generated by Django 6.1.1 on 2026-09-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя мастера')),
                ('photo', models.ImageField(upload_to='master/', verbose_name='Фото мастера')),
                ('about', models.TextField(verbose_name='О мастере')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Информация о мастере',
                'verbose_name_plural': 'Информация о мастере',
            },
        ),
    ]
