# Generated by Django 6.1.1 on 2026-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('vk', 'VK'), ('avito', 'Avito'), ('yandex', 'Яндекс'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('image', models.ImageField(upload_to='reviews/screenshots/', verbose_name='Скрин отзыва')),
                ('is_featured', models.BooleanField(default=False, verbose_name='На главной')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Скрин отзыва',
                'verbose_name_plural': 'Скрины отзывов',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото отзыва'),
        ),
    ]
