# Generated by Django 6.1.1 on 2026-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_screenshotreview_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshotreview',
            name='source',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('max', 'MAX'), ('telegram', 'Telegram'), ('vk', 'VK'), ('avito', 'Avito'), ('yandex', 'Яндекс'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник'),
        ),
    ]
