# Generated by Django 6.1.1 on 2026-09-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_work_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_views', to='portfolio.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Просмотр работы',
                'verbose_name_plural': 'Просмотры работ',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('work', 'user'), name='unique_user_work_view')],
            },
        ),
    ]
